sudo: required
langauge: generic
services:
  - docker

before_install:
  - docker build -t kristopherbosco/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kristopherbosco/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-213644390615"
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY